function About()
{
  return(
    <div class="about">
  <div class="about-1">
    <h1>ABOUT ME</h1>
    <div class="about-2">
      <h1>HELLO I AM MOHAMMED FAZIL</h1>
    <p>AS I AM FRESHER ,I COMPLETED BCA (BACHELOR OF COMPUTER APPLICATION) IN 2021 GRADUATE FROM(THIRUVALLUVAR UNIVERSITY) WITH A PASSION FOR IT FIELD IN FULL STACK DEVELOPMENT.AND I HAVE DEVELOPED A STRONG FOUNFDATION IN [FONTEND,BACKEND] AND AS I COMPLETED PROJECT BASED FOR THIS AND I AM EAGER TO APPLY MY KNOWLEDGE IN PROFFESSIONAL SETTING</p>
    </div>
  </div>
</div>
  )
}
export default (About)